version: '3.8'

services:
  backend:
    build: ./incede_hrms_backend
    ports:
      - "8080:8080"
    networks:
      - hrms-net
    restart: always
    depends_on:
      - postgres

  frontend:
    build: ./incede_hrms_frontend
    ports:
      - "3000:80"
    networks:
      - hrms-net
    depends_on:
      - backend
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: hrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - hrms-net
    restart: always

networks:
  hrms-net:
