# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./incede_hrms_backend
    ports:
      - "8080:8080"
    networks:
      - hr-net
    restart: always


  frontend:
    build: ./incede_hrms_frontend
    ports:
      - "3000:80"
    networks:
      - hr-net
    depends_on:
      - backend
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: hrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - hr-net
    restart: always


networks:
  hr-net:
